version: "3.1"

services:
  redis:
    image: redis:5
    container_name: redis_test
    ports:
      - 6479:6379
  db:
    image: postgres:11-alpine
    container_name: postgres_test
    restart: always
    environment:
      POSTGRES_DB: postgres_test
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5532:5432
