version: "3.1"

services:
  redis:
    image: redis:5
    container_name: redis
    ports:
      - 6379:6379
  db:
    image: postgres:11-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: datahub_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
